case class Entity(var LATEST_USED_STORAGE_SIZE_DLY: Long,
                  var AGGR_COUNT_DLY: Long,
                  var PRS_ID: Long,
                  var UD_ID: String,
                  var EVENT_TYPE: String,
                  var PLATFORM: String,
                  var OS_VERSION: String,
                  var APPLICATION: String,
                  var BUNDLE_ID: String,
                  var KV_ID: String,
                  var SERVER_ERROR: String,
                  var SERVICE_TYPE: String,
                  var EVENT_DATE_1: String,
                  var EVENT_DATE_2: String,
                  var EVENT_TIME_EPOCH: Long,
                  var TYPE: String)